title: Taidekuja- ja Taidepolkuhaku
layout: vertical
description: |
  Lomakkeella haetaan taidekuja- ja taidepolkupöytäpaikkaa Tracon-tapahtumasta 6.-8.9.2024.

  Haku on auki 1.4. - 26.4.2024.

   <strong>Lisätietoja hausta:</strong> <a href="https://2024.tracon.fi/taidekujahaku/">Hae taidekujalle ja taidepolulle</a>.

fields:
  - type: StaticText
    title: Perustiedot
    slug: basic_info_title

  - slug: name
    title: Etunimi ja sukunimi
    type: SingleLineText
    required: true

  - slug: email
    title: Vastuuhenkilön sähköposti
    type: SingleLineText
    required: true

  - slug: location_select
    title: Myyntipaikan valinta
    helpText: "Valitse kaikki sopivat vaihtoehdot. Sinulle tarjotaan vain valitsemiasi paikkoja."
    type: StaticText

  - slug: artist_alley
    title: Taidekujan valinta
    type: MultiSelect
    required: false
    choices:
      - slug: alley_sat
        title: Lauantai
      - slug: alley_sun
        title: Sunnuntai
      - slug: alley_satsun
        title: Lauantai ja sunnuntai

  - slug: art_trail
    title: Taidepolun valinta
    type: MultiSelect
    required: false
    choices:
      - slug: trail_fri
        title: Perjantai
      - slug: trail_sat
        title: Lauantai
      - slug: trail_sun
        title: Sunnuntai

  - slug: portfolio
    title: Portfolio
    helpText: "Yksi (1) portfoliolinkki per taiteilija / ryhmä. Tarkistathan ettei lomake ole suojattu salasanalla tai edellytä kirjautumista."
    type: SingleLineText
    required: true

  - slug: reserve
    title: Varasija
    helpText: "Ilmaise halukkuutesi varasijalle. Varasijallisista koostetaan lista joita lähestytään mikäli paikkoja vapautuu. Erillistä varasijalistaa ei julkaista tai ilmoiteta. Voit vapaassa kentässä täsmentää kuinka lyhyellä varoitusajalla olet valmis tulemaan paikalle."
    type: SingleSelect
    required: true
    choices:
      - slug: "no"
        title: En halua jonottaa varasijaa
      - slug: "yes"
        title: Haluan jonottaa varasijaa
      - slug: "fast"
        title: Pääsen nopeallakin varoitusajalla paikalle

  - type: StaticText
    title: Taustatiedot
    slug: background_info

  - slug: experience
    title: Kokemus
    type: MultiSelect
    choices:
      - slug: exp_new
        title: Aloittelija (alle viisi (5) kujaa takana)
      - slug: exp_first
        title: Ensikertaa Tracon -tapahtumassa

  - slug: location
    title: Osallistutko tapahtumaan Suomesta vai ulkomailta
    type: SingleSelect
    required: true
    choices:
      - slug: finland
        title: Suomesta
      - slug: abroad
        title: Ulkomailta

  - slug: helper
    title: Tuleeko mukanasi avustaja
    type: SingleSelect
    required: true
    choices:
      - slug: help_yes
        title: Kyllä
      - slug: help_no
        title: Ei

  - slug: help_name
    title: Avustajan nimi
    type: SingleLineText
    required: false

  - slug: comments
    title: Vapaa sana
    helpText: "Vapaa alue lisätiedoille ja toiveille. Ilmaisethan jos tarvitset esteettömyyden huomiointia taidekujan tai taidepolun sijoituksessa, jotta voimme järjestää mahdollisimman sujuvan pääsyn pöydän ääreen."
    type: MultiLineText
    required: false

  - type: StaticText
    title: Taiteilijatiedot sivuille
    helpText: "Mikäli toimitte kollektiivina, täytättehän vain yhden taiteilijakohdan. Jätä ylimääräiset kentät tyhjäksi. Huom. avatar-kuvan koko 200 px x 200 px"

    slug: artist_info
  - type: StaticText
    title: Taiteilijan 1 tiedot
    slug: artist_info1

  - slug: artist_name1
    title: Taiteilijanimi
    type: SingleLineText
    required: true

  - slug: artist_site1
    title: Kotisivu
    type: SingleLineText
    required: true

  - slug: artist_avatar1
    title: Avatar
    type: FileUpload
    required: true

  - slug: artist_desc1
    title: Lyhyt kuvaus nettisivuille
    type: SingleLineText
    required: true

  - type: StaticText
    title: Taiteilijan 2 tiedot
    slug: artist_info2

  - slug: artist_name2
    title: Taiteilijanimi
    type: SingleLineText
    required: false

  - slug: artist_site2
    title: Kotisivu
    type: SingleLineText
    required: false

  - slug: artist_avatar2
    title: Avatar
    type: FileUpload
    required: false

  - slug: artist_desc2
    title: Lyhyt kuvaus nettisivuille
    type: SingleLineText
    required: false

  - type: StaticText
    title: Taiteilijan 3 tiedot
    slug: artist_info3

  - slug: artist_name3
    title: Taiteilijanimi
    type: SingleLineText
    required: false

  - slug: artist_site3
    title: Kotisivu
    type: SingleLineText
    required: false

  - slug: artist_avatar3
    title: Avatar
    type: FileUpload
    required: false

  - slug: artist_desc3
    title: Lyhyt kuvaus nettisivuille
    type: SingleLineText
    required: false
